markdown: kramdown
kramdown:
  input: GFM

title: "Scala Documentation"
description: "Documentation for the Scala programming language - Tutorials, Overviews, Cheatsheets, and more."
keywords:
- Scala
- Documentation
- Tutorial
- Scala Programming Language
- Reference
- Cheatsheet
- Article
- Document
- Guide

scala-version: 2.12.2

collections:
  style:
    output: true
  overviews:
    output: true
  books:
    output: false
  ja: # Japanese translations
    output: true
    permalink: /:collection/:path.html
  zh-cn: # Chinese (Simplified) translations
    output: true
    permalink: /:collection/:path.html
  ru: # Russian translations
    output: true
    permalink: /:collection/:path.html
  es: # Spanish translations
    output: true
    permalink: /:collection/:path.html

highlighter: rouge
permalink: /:categories/:title.html:output_ext
baseurl:
exclude: ["vendor"]
gems:
  - jekyll-redirect-from
